Merging branch that has tunable coupler elements and other significant additions
q-optimize/c3 pull request #13
Opened 2021-01-15 17:53 UTC by fedroy

Warning:
Not all the added code has been adjusted to the new structure and no testing has been added for the new code.
During merge I probably reintroduced some removed code and some annoying commented code.
We can try to address these problems before merge or after, not sure what is best practice.

Niklas Glaser (@GlaserN) implemented a significant portion of the changes below.

Changes summary:
Added feature to calculate an operator expectation value
Made separate signal generation chain for each control line
Wrote new pulse shapes
Added more devices emualting noise, markovian and non (might need update to new code structure)
Added fidelities specific for 2 qubit gates with coupler
Wrote robust optimal control in a new optimizer function
Added Netzero envelopes
New flux tunable elements (like symmetric and asymmetric transmons)
Improved hamiltonian reordering process
Changed all matrix exponentiations to the tensorflow expm function

2021-01-15 18:05 UTC, lazyoracle commented
@fedroy Any way we can bring the test coverage back up to where it was? Codecov suggests that the coverage will go down by 6.5% if we merge which is quite significant. If you think there isn't much to be done on the tests front, then I will approve and merge this.

2021-01-15 22:24 UTC, shaimach commented
Can you elaborate what is the added functionality in terms of
* Robust gates
* non-Markovian noise


On Fri, 15 Jan 2021, 20:05 Anurag Saha Roy, <notifications@github.com>
wrote:

> @fedroy <https://github.com/fedroy> Any way we can bring the test
> coverage back up to where it was? Codecov suggests that the coverage will
> go down by 6.5% if we merge which is quite significant. If you think there
> isn't much to be done on the tests front, then I will approve and merge
> this.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/q-optimize/c3/pull/13#issuecomment-761096271>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH3Q4IOHTHWJNO7MUHJBTLS2B7X7ANCNFSM4WEMXGMQ>
> .
>

2021-01-16 08:51 UTC, lazyoracle requested changes
> Warning:
Not all the added code has been adjusted to the new structure and no testing has been added for the new code.
During merge I probably reintroduced some removed code and some annoying commented code.
We can try to address these problems before merge or after, not sure what is best practice.

We definitely want to keep PRs self contained. Which means if there is code that got reintroduced which was previously removed in a refactor/cleanup, we most definitely want to tackle it in this PR before merging it into the `dev` or `master`. This is coming from the idea that those branches should be clean and stable. And for merges with the number of commits as here, we definitely want to squash all of it into a single commit, otherwise it will be extremely difficult to keep track of things. I would thus very strongly recommend that we do all the clean-up in this branch which probably at least includes the following:
* Ensure any code that was previously removed (including commented sections) has not crept back in here
* Ensure all sections of the codebase are up to date with the new structure. Not doing this will affect other features that are simultaneously being developed/merged.
* Ensure at least basic testing is added. Firstly, because we do not want to reduce our test coverage. Secondly, we wont know if someone else comes and messes up all the extensive work done by @fedroy @GlaserN without adequate tests for this PR.

I am tagging this PR to `on-hold` while we keep adding more commits to ensure no residual code creeps back and there are adequate tests.

2021-01-16 10:28 UTC, fedroy commented
> Can you elaborate what is the added functionality in terms of * Robust gates * non-Markovian noise

@GlaserN wrote a new version of the c1 optimizer that allows for optimization over multiple experiment instances, with variation in model parameters. This should allow for the implementation of robust optimal control. Niklas could comment further, maybe the way he implemented it is slightly different.

I wrote a noise box in the signal generation that introduces Random telegraph signal noise or sum thereof (leading to 1/f type noise). Niklas also has implemented a general filter function object to include the presence of filters along the line.

2021-01-16 11:13 UTC, shaimach commented
Re. new features of robustness, control line noise and filter functions
(IIR?):

These are great.

The growing number of features and capabilities means we need to put some
effort into high-level documentation, describing in general terms the
current features and capabilities, and linking down to API and JSON
detailed documentation.

On Sat, 16 Jan 2021, 12:28 Federico Roy, <notifications@github.com> wrote:

> Can you elaborate what is the added functionality in terms of * Robust
> gates * non-Markovian noise
>
> @GlaserN <https://github.com/GlaserN> wrote a new version of the c1
> optimizer that allows for optimization over multiple experiment instances,
> with variation in model parameters. This should allow for the
> implementation of robust optimal control. Niklas could comment further,
> maybe the way he implemented it is slightly different.
>
> I wrote a noise box in the signal generation that introduces Random
> telegraph signal noise or sum thereof (leading to 1/f type noise). Niklas
> also has implemented a general filter function object to include the
> presence of filters along the line.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/q-optimize/c3/pull/13#issuecomment-761540436>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH3Q4M6XJCOJIUP7HCM7JLS2FS5RANCNFSM4WEMXGMQ>
> .
>

2021-01-25 16:25 UTC, fedroy reviewed
Minor cleanups

2021-01-25 16:25 UTC, fedroy commented on c3/system/chip.py
>  class SymmetricTransmon(PhysicalComponent):
Make symmetric transmon a special case of Asymmetric transmon

2021-01-25 16:25 UTC, fedroy commented on c3/system/model.py
> +            # TODO test dressing of FR
leave todo, move to issue if needed but remove commented code below.

2021-01-25 16:25 UTC, fedroy commented on c3/utils/utils.py
> +        pass
fix it in windows?

2021-01-25 16:27 UTC, nwittler requested changes
- Some minor cleanup to be done where indicated. 
- new devices to be made compatible with signal chain
- more tests

After merge:
- Model learning code needs some love

2021-01-25 16:27 UTC, nwittler commented on c3/generator/devices.py
>  import os
All devices need to conform to the signal chain usage, i.e. implement `process()`. Confirm with tests.

2021-01-25 16:27 UTC, nwittler commented on c3/libraries/estimators.py
> +        # print(f"{pops=}\n{scale=}\n{shots=}\n{std=}")
Revert to the old one. Make this one user-defined.

2021-01-25 16:27 UTC, nwittler commented on c3/libraries/fidelities.py
> +def lindbladian_cphase_comp_sub(U_dict: dict, index, dims, eval, proj=True):
Move these functions to the user definitions.

2021-01-25 16:27 UTC, nwittler commented on c3/libraries/fidelities.py
> +    # gate = list(U_dict.keys())[0]
Delete commented code.

2021-01-25 16:27 UTC, nwittler commented on c3/libraries/fidelities.py
> +        # real_cliffords = evaluate_sequences(U_dict, cliffords_decomp)
Delete comments.

2021-01-25 16:36 UTC, lazyoracle commented
The branch is out of date with `dev` (since the SNAIL PR), needs to be rebased on `dev`. @fedroy had been working on the private repo branch, so might be useful to switch development to this branch instead to stay in sync

2021-01-26 16:50 UTC, nwittler reviewed
Looks good.

2021-01-26 17:29 UTC, nwittler commented on c3/generator/devices.py
>  import os
We'll do this in dev.

2021-01-26 17:30 UTC, nwittler submitted a review, later dismissed
Most significant things fixed. Some larger issues are left for fixing in dev.

2021-01-26 17:35 UTC, lazyoracle requested changes
Several tests are failing, at import level, even before running the tests. Would need to fix the tests or the code before its ready to merge.

2021-01-26 18:27 UTC, lazyoracle approved these changes

2021-01-26 18:29 UTC, nwittler approved these changes
Let's keep the precision issue in mind.

2021-01-26 18:32 UTC, merged