Test quick setup
q-optimize/c3 pull request #182
Opened 2022-03-23 14:03 UTC by nwittler

## What
Add a small test for signal generation from a quick setup.

## Why
Check for changes in the quick setup.

## How
Compare generated signals to stored reference.

## Checklist
Please include and complete the following checklist. Your Pull Request is (in most cases) not ready for review until the following have been completed. You can create a draft PR while you are still completing the checklist. Check the [Contribution Guidelines](https://github.com/q-optimize/c3/blob/dev/CONTRIBUTING.md) for more details. You can mark an item as complete with the `- [x]` prefix

- [ ] Tests - Added unit tests for new code, regression tests for bugs and updated the integration tests if required
- [ ] Formatting & Linting - `black` and `flake8` have been used to ensure styling guidelines are met
- [ ] Type Annotations - All new code has been type annotated in the function signatures using type hints
- [ ] Docstrings - Docstrings have been provided for functions in the `numpydoc` style
- [ ] Documentation - The tutorial style documentation has been updated to explain changes & new features
- [ ] Notebooks - Example notebooks have been updated to incorporate changes and new features
- [ ] Changelog - A short note on this PR has been added to the Upcoming Release section

2022-03-23 14:39 UTC, lazyoracle requested changes

2022-03-23 14:39 UTC, lazyoracle commented on test/test_quick_setup.py
> +    np.testing.assert_allclose(
One possible standard we might want to enforce is that original test writers should provide explicit `atol` or `rtol` values for tests that use `assert_allclose` type functionality. These tolerances should be the maximum acceptable worst case figures. This ensures that we don't tamper with tests later on when introducing some new feature or fixing a bug, with the assumption that the original test writer already accounted for the worst case figures and a failing test indicates something other than precision issues.

2022-03-24 11:39 UTC, nwittler commented on test/test_quick_setup.py
> +    np.testing.assert_allclose(
Good idea. Done.

2022-03-24 11:43 UTC, lazyoracle commented
Do you mind if I rebase and cleanup a bit of the git history in this PR and then force push the branch? 😆

2022-03-24 11:49 UTC, nwittler commented
> Do you mind if I rebase and cleanup a bit of the git history in this PR and then force push the branch? 😆

Go ahead, that's magic to me.

2022-03-24 12:59 UTC, lazyoracle approved these changes

2022-03-24 13:29 UTC, merged