Hamiltonian generation and instruction handling
q-optimize/c3 pull request #87
Opened 2021-05-11 17:53 UTC by GlaserN

This merge most importantly has the ability to request time sliced hamiltonians form the LineComponents to get time dependent drift hamiltonians. Furthermore awg signal generation has been moved to the Instruction object giving the pulse positioning more options.

Many more new features and fixes are included in this merge, including:

- Device Hamiltonian can be time dependent essentially not separating anymore between h0 and hctrl but time sliced Hamiltonian already in model. Default is still with control field hamiltonians. 
- Additional chip devices (CShuntFluxQubit, Fluxonium, Duffing oscillator up to 6th order)
- Moved AWG signal generation to the Instruction object instead. 
- Pulses can now be triggered to happen after a component of the instruction is finished
- Quantity object operations are performed and return a quantity object
- Set value has extend bounds option and has better tensorflow compatibility
- Quantity: get and set limits functions added
- Add FFT convolution based filters that can be described by a Stepfunction.
- New Logger class for optimizer implemented for TensorBoard
- Fixed unitary fidelity for gates acting on multiple qubits. Get perfect gate of instructions now behaves as expected for multi-qubit gates. Concatenated ideal gates can be defined again.
- Propagation has now option for batching (useful only when not evaluating gradient)
- Additional functions in parameter map
- Slightly enhanced matrix cutting 
- Better handling of overly dressed states
- Added gradient free scipy lbfgs algorithm
- Additional default gates according to QASM notation
- Added shapes
- Removed all json occurrences
- Vectorize lindblad propagation
- Length of devices is forced to be a multiple of the resolution

2021-05-12 09:44 UTC, lazyoracle requested changes

2021-05-12 09:44 UTC, lazyoracle commented on c3/utils/utils.py
> +    except PermissionError:
The `OSError` above is expected to subsume this `PermissionError` which would never be reached in that case and is possibly redundant.

2021-05-12 09:44 UTC, lazyoracle commented on c3/system/chip.py
> +import scipy.optimize
Multiple imports of `scipy.optimize` in this block, possibly rendering the previous `from scipy.optimize import fmin` redundant.

2021-05-12 09:59 UTC, lazyoracle submitted a review, later dismissed

2021-05-12 10:38 UTC, lazyoracle commented
The test coverage goes down by more than a percent, do we wish to make this pull request complete by adding tests in this PR or would that come separately?

2021-05-16 19:48 UTC, lazyoracle commented
As noted by @shaimach for the purpose of reporting metrics and tracking changes, contributors/reviewers with write access (in this case @fedroy), please make sure the merge commit message (the one which appears when you try to `Merge pull request` on Github) for this PR has the following template. This PR description is already descriptive enough that it could form the basis for the multi-line detailed merge commit message:

> Short 1-line description of key feature/bug-fix with associated issue numbers if any (can go in the commit heading in Github PR merge UI)
> 
> (The part below goes in the merge commit message details)
> Contributors: Full name (and not Github handle) of all contributors to this PR, irrespective of who made the code commits.
> Longer multi-line description, typically in the form of a detailed list of various features implemented with any additional insights/remarks on the implementations etc.

2021-05-17 07:57 UTC, fedroy approved these changes
Looked at all changes together and I can confirm that the code is ready for being merged.
Lots of useful new feature that also align well with future development.

2021-05-17 08:19 UTC, lazyoracle approved these changes
LGTM!

2021-05-17 08:38 UTC, merged